pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'ssh://git@sourcecode.socialcoding.bosch.com:7999/~vko3hc/appsettingcicd.git',
                    branch: 'master',
                    credentialsId: '1'
                )
            }
        }
        stage('Restore Dependencies'){
            steps{
                //restore nuget packages
                //step: run shell command to restore dependencies nescessary
                bat 'dotnet restore C:\\Project\\ConsoleAppSMTP\\ConsoleAppSMTP.sln'
            }
        }
        stage('Build Project'){
            steps{
                //Build Project and get the .dll files
                bat 'dotnet build ConsoleAppSMTP.sln --configuration Release'
            }
        }
        stage('Archive Artifacts'){
            steps{
                //Archive the .dll files in Jenkins
                archiveArtifacts artifacts: '**/bin/Release/**/*.dll, fingerprint: true'
            }
        }
        stage('Deploy to IIS') {
            steps {
                // Corrected copy command with double backslashes and using 'copy' keyword
                bat 'copy "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Continious Integration and Deployment\\ConsoleAppSMTP\\bin\\Release\\*.dll" "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Continious Integration and Deployment\\ConsoleAppSMTP\\bin\\Deploy"'

                // Restart IIS to apply the changes
                bat 'iisreset /restart'
            }
        }
    }
}